# Generated by Django 3.2.7 on 2021-10-05 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='foods',
            field=models.ManyToManyField(related_name='markets', to='backend.Food'),
        ),
    ]
