# Generated by Django 3.2.7 on 2021-11-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='markets',
            field=models.ManyToManyField(to='backend.Market'),
        ),
    ]
