# Generated by Django 3.2.7 on 2021-09-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_market'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='market',
            name='img_field',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
