# Generated by Django 3.2.7 on 2021-11-23 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='img',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='market',
            name='img',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
